//! Export a Verus transition-system model to TLA+.
//!
//! The exporter reads the typed VIR crate, finds the model's `(State, init,
//! next, invariants)` triple, and prints TLA+ operators for every spec
//! function the triple reaches. It keys on nothing from any one project:
//! datatypes become records, `vstd` collections become TLA+ sequences, sets
//! and functions, spec functions become operators, and a quantifier is
//! bounded from its own guard. Whatever it cannot express it refuses with a
//! source location, and whatever it cannot bound becomes a `CONSTANT` the
//! model config must supply. Both lists come back in the [`Report`].
//!
//! Three ways of writing a transition system are recognised:
//!
//! * hand-rolled: `init(s: S) -> bool`, `next(pre: S, post: S) -> bool` in
//!   the named module, invariants the module's other `(S) -> bool` spec
//!   functions;
//! * VerusSync: `State::init(post)`, `State::next(pre, post)` generated by
//!   `state_machine!`, invariants the `#[invariant]` methods;
//! * verus-tla: `init()` and `next()` returning `spec_fn` closures over the
//!   state, with `Action { precondition, transition }` records inlined.
//!
//! The state datatype's fields are the TLA+ variables. A parameter of the
//! state type in the pre role prints as the unprimed variables, one in the
//! post role as the primed ones, so `post.f == e` becomes `f' = e`, which is
//! the shape TLC needs to assign a primed variable.

use crate::ast::*;
use crate::ast_util::{fun_as_friendly_rust_name, path_as_friendly_rust_name};
use serde::Serialize;
use std::collections::{BTreeSet, HashMap, HashSet};
use std::sync::Arc;

/// Something the export could not express; the `.tla` says so in a comment
/// at the site and prints `TRUE` (a guard) or the Rust text.
#[derive(Debug, Clone, Serialize)]
pub struct Refusal {
    pub what: String,
    pub location: String,
    pub in_function: String,
}

/// A quantifier the export could not bound; the `.cfg` skeleton carries a
/// `CONSTANT` for it.
#[derive(Debug, Clone, Serialize)]
pub struct Hole {
    pub variable: String,
    pub typ: String,
    pub constant: String,
    pub location: String,
    pub in_function: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct Report {
    pub module: String,
    pub shape: String,
    pub state_type: String,
    pub variables: Vec<String>,
    pub init: String,
    pub next: String,
    pub actions: Vec<String>,
    pub invariants: Vec<String>,
    pub operators: usize,
    pub holes: Vec<Hole>,
    pub refusals: Vec<Refusal>,
}

pub struct Export {
    pub tla: String,
    pub cfg: String,
    pub report: Report,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Role {
    Pre,
    Post,
}

#[derive(Clone)]
struct Env {
    /// State-typed parameters in a pre or post role.
    roles: HashMap<VarIdent, Role>,
    /// Every other variable in scope, by its printed name.
    names: HashMap<VarIdent, String>,
    /// Variables bound to a closure or record value, kept symbolically so a
    /// later application or field selection can be reduced.
    values: HashMap<VarIdent, (Expr, Box<Env>)>,
}

impl Env {
    fn new() -> Self {
        Env { roles: HashMap::new(), names: HashMap::new(), values: HashMap::new() }
    }
    fn name(&self, v: &VarIdent) -> String {
        self.names.get(v).cloned().unwrap_or_else(|| ident_name(v))
    }
}

struct Exporter<'a> {
    krate: &'a Krate,
    datatypes: HashMap<Path, Datatype>,
    functions: HashMap<Fun, Function>,
    state_path: Path,
    state_fields: Vec<String>,
    /// Operator definitions in dependency order.
    defs: Vec<String>,
    /// Functions already emitted or being emitted (for recursion).
    emitted: HashSet<Fun>,
    emitting: HashSet<Fun>,
    recursive: BTreeSet<String>,
    /// Operator name per function, unique.
    op_names: HashMap<Fun, String>,
    used_names: HashSet<String>,
    holes: Vec<Hole>,
    refusals: Vec<Refusal>,
    constants: BTreeSet<String>,
    current: String,
}

fn ident_name(v: &VarIdent) -> String {
    let s = v.0.to_string();
    let s: String = s.chars().map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' }).collect();
    let s = s.trim_end_matches('_').to_string();
    let s = if s.is_empty() { "v".to_string() } else { s };
    // TLA+ identifiers cannot start with a digit; a few words are reserved.
    let s = if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) { format!("v{s}") } else { s };
    match s.as_str() {
        "ASSUME" | "ELSE" | "LOCAL" | "UNION" | "ASSUMPTION" | "ENABLED" | "MODULE" | "VARIABLE"
        | "AXIOM" | "EXCEPT" | "OTHER" | "VARIABLES" | "CASE" | "EXTENDS" | "SF_" | "WF_"
        | "CHOOSE" | "IF" | "SUBSET" | "WITH" | "CONSTANT" | "IN" | "THEN" | "CONSTANTS"
        | "INSTANCE" | "THEOREM" | "DOMAIN" | "LET" | "UNCHANGED" | "STRING" | "BOOLEAN"
        | "TRUE" | "FALSE" | "Nat" | "Int" | "Seq" | "Len" | "Append" | "Head" | "Tail" => {
            format!("{s}_")
        }
        _ => s,
    }
}

fn last_segment(path: &Path) -> String {
    path.segments.last().map(|s| s.to_string()).unwrap_or_else(|| "anon".into())
}

fn span_string(span: &crate::messages::Span) -> String {
    span.as_string.clone()
}

/// The datatype a type names, through decorations and boxing.
fn typ_datatype(typ: &Typ) -> Option<Path> {
    match &**typ {
        TypX::Datatype(Dt::Path(p), _, _) => Some(p.clone()),
        TypX::Decorate(_, _, t) => typ_datatype(t),
        TypX::Boxed(t) => typ_datatype(t),
        _ => None,
    }
}

/// The friendly name of a type, for holes and constants.
fn typ_name(typ: &Typ) -> String {
    match &**typ {
        TypX::Bool => "bool".into(),
        TypX::Int(_) => "int".into(),
        TypX::Datatype(Dt::Path(p), args, _) => {
            let base = last_segment(p);
            if args.is_empty() {
                base
            } else {
                format!("{base}_{}", args.iter().map(typ_name).collect::<Vec<_>>().join("_"))
            }
        }
        TypX::Datatype(Dt::Tuple(n), _, _) => format!("tuple{n}"),
        TypX::Decorate(_, _, t) | TypX::Boxed(t) => typ_name(t),
        TypX::TypParam(x) => x.to_string(),
        _ => "T".into(),
    }
}

/// The variable an expression reads, through place reads and boxing.
fn read_var(e: &Expr) -> Option<VarIdent> {
    match &e.x {
        ExprX::Var(v) => Some(v.clone()),
        ExprX::ReadPlace(p, _) => place_var(p),
        ExprX::UnaryOpr(UnaryOpr::Box(_) | UnaryOpr::Unbox(_), inner) => read_var(inner),
        ExprX::Block(stmts, Some(tail)) if stmts.is_empty() => read_var(tail),
        _ => None,
    }
}

fn place_var(p: &Place) -> Option<VarIdent> {
    match &p.x {
        PlaceX::Local(v) => Some(v.clone()),
        PlaceX::DerefMut(inner) | PlaceX::ModeUnwrap(inner, _) => place_var(inner),
        PlaceX::Temporary(e) | PlaceX::WithExpr(e, _) => read_var(e),
        _ => None,
    }
}

/// Strip wrappers that carry no meaning here (empty blocks, boxing, place
/// temporaries) to reach the expression underneath.
fn peel(e: &Expr) -> Expr {
    match &e.x {
        ExprX::Block(stmts, Some(tail)) if stmts.is_empty() => peel(tail),
        ExprX::UnaryOpr(UnaryOpr::Box(_) | UnaryOpr::Unbox(_), inner) => peel(inner),
        ExprX::ReadPlace(p, _) => match &p.x {
            PlaceX::Temporary(inner) | PlaceX::WithExpr(inner, _) => peel(inner),
            _ => e.clone(),
        },
        ExprX::WithTriggers { body, .. } => peel(body),
        _ => e.clone(),
    }
}

fn sanitize(s: &str) -> String {
    s.chars().map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' }).collect()
}

/// Split a conjunction into its conjuncts.
fn conjuncts(e: &Expr) -> Vec<Expr> {
    match &e.x {
        ExprX::Logical(LogicalOp::And, a, b) => {
            let mut v = conjuncts(a);
            v.extend(conjuncts(b));
            v
        }
        _ => vec![e.clone()],
    }
}

fn mentions(e: &Expr, v: &VarIdent) -> bool {
    let mut found = false;
    crate::ast_visitor::expr_visitor_walk(e, &mut |x: &Expr| {
        if let ExprX::Var(u) = &x.x {
            if u == v {
                found = true;
            }
        }
        crate::visitor::VisitorControlFlow::Recurse
    });
    found
}

/// A known `vstd` operation, by the friendly name of its function. The
/// name carries an `impl&%N` segment rather than the type, so the key is
/// the module (seq, set, map, and their `_lib` siblings) plus the method.
fn vstd_op(name: &str) -> Option<&'static str> {
    let segs: Vec<&str> = name.split("::").collect();
    if segs.len() < 3 || segs[0] != "vstd" {
        return None;
    }
    let module = segs[1].trim_end_matches("_lib");
    let method = segs[segs.len() - 1];
    Some(match (module, method) {
        ("seq", "len") => "seq_len",
        ("seq", "index") | ("seq", "spec_index") => "seq_index",
        ("seq", "push") => "seq_push",
        ("seq", "update") => "seq_update",
        ("seq", "subrange") => "seq_subrange",
        ("seq", "add") => "seq_add",
        ("seq", "empty") => "seq_empty",
        ("seq", "last") => "seq_last",
        ("seq", "first") => "seq_first",
        ("seq", "drop_first") => "seq_drop_first",
        ("seq", "drop_last") => "seq_drop_last",
        ("seq", "take") => "seq_take",
        ("seq", "skip") => "seq_skip",
        ("seq", "new") => "seq_new",
        ("seq", "contains") => "seq_contains",
        ("seq", "ext_equal") => "ext_equal",
        ("set", "contains") => "set_contains",
        ("set", "insert") => "set_insert",
        ("set", "remove") => "set_remove",
        ("set", "empty") => "set_empty",
        ("set", "union") => "set_union",
        ("set", "intersect") => "set_intersect",
        ("set", "difference") => "set_difference",
        ("set", "subset_of") => "set_subset_of",
        ("set", "len") => "set_len",
        ("set", "finite") => "set_finite",
        ("set", "is_empty") => "set_is_empty",
        ("set", "ext_equal") => "ext_equal",
        ("set", "full") => "set_full",
        ("map", "dom") => "map_dom",
        ("map", "index") | ("map", "spec_index") => "map_index",
        ("map", "insert") => "map_insert",
        ("map", "remove") => "map_remove",
        ("map", "empty") => "map_empty",
        ("map", "contains_key") => "map_contains_key",
        ("map", "len") => "map_len",
        ("map", "values") => "map_values",
        ("map", "ext_equal") => "ext_equal",
        _ => return None,
    })
}

/// Whether a type carries a spec_fn anywhere: such values are reduced
/// symbolically and never printed.
fn typ_has_specfn(typ: &Typ, datatypes: &HashMap<Path, Datatype>, seen: &mut HashSet<Path>) -> bool {
    match &**typ {
        TypX::SpecFn(..) | TypX::AnonymousClosure(..) | TypX::FnDef(..) => true,
        TypX::Datatype(Dt::Path(p), args, _) => {
            if args.iter().any(|a| typ_has_specfn(a, datatypes, seen)) {
                return true;
            }
            if !seen.insert(p.clone()) {
                return false;
            }
            datatypes
                .get(p)
                .map(|d| d.x.variants.iter().any(|v| v.fields.iter().any(|f| typ_has_specfn(&f.a.0, datatypes, seen))))
                .unwrap_or(false)
        }
        TypX::Datatype(Dt::Tuple(_), args, _) => args.iter().any(|a| typ_has_specfn(a, datatypes, seen)),
        TypX::Decorate(_, _, t) | TypX::Boxed(t) => typ_has_specfn(t, datatypes, seen),
        _ => false,
    }
}

impl<'a> Exporter<'a> {
    fn refuse(&mut self, what: impl Into<String>, span: &crate::messages::Span) -> String {
        let what = what.into();
        self.refusals.push(Refusal {
            what: what.clone(),
            location: span_string(span),
            in_function: self.current.clone(),
        });
        format!("TRUE (* refused: {} *)", what.replace("*)", "* )"))
    }

    fn state_field_names(&self) -> Vec<String> {
        self.state_fields.clone()
    }

    fn is_state_typ(&self, typ: &Typ) -> bool {
        typ_datatype(typ).map(|p| p == self.state_path).unwrap_or(false)
    }

    /// The unique operator name for a function.
    fn op_name(&mut self, fun: &Fun) -> String {
        if let Some(n) = self.op_names.get(fun) {
            return n.clone();
        }
        let friendly = fun_as_friendly_rust_name(fun);
        let segs: Vec<&str> = friendly.split("::").collect();
        let mut candidate = ident_name(&VarIdent(Arc::new(segs.last().unwrap_or(&"f").to_string()), VarIdentDisambiguate::AirLocal));
        if self.used_names.contains(&candidate) && segs.len() >= 2 {
            candidate = format!("{}_{}", sanitize(segs[segs.len() - 2]), candidate);
        }
        let mut n = 2;
        let base = candidate.clone();
        while self.used_names.contains(&candidate) {
            candidate = format!("{base}{n}");
            n += 1;
        }
        self.used_names.insert(candidate.clone());
        self.op_names.insert(fun.clone(), candidate.clone());
        candidate
    }

    /// The record for a whole state in the given role.
    fn state_record(&self, role: Role) -> String {
        let prime = if role == Role::Post { "'" } else { "" };
        format!(
            "[{}]",
            self.state_fields.iter().map(|f| format!("{f} |-> {f}{prime}")).collect::<Vec<_>>().join(", ")
        )
    }

    // ─── expressions ────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr, env: &Env) -> String {
        match &e.x {
            ExprX::Const(c) => match c {
                Constant::Bool(true) => "TRUE".into(),
                Constant::Bool(false) => "FALSE".into(),
                Constant::Int(i) => i.to_string(),
                Constant::StrSlice(s) => format!("\"{}\"", s.replace('"', "\\\"")),
                Constant::Real(r) => r.clone(),
                Constant::ByteStr(_) => self.refuse("byte string literal", &e.span),
                Constant::Char(c) => format!("\"{}\"", c),
                Constant::Float32(_) | Constant::Float64(_) => self.refuse("float literal", &e.span),
            },
            ExprX::Var(v) => {
                if let Some(role) = env.roles.get(v) {
                    self.state_record(*role)
                } else {
                    env.name(v)
                }
            }
            ExprX::VarAt(..) => self.refuse("old(...) reference", &e.span),
            ExprX::ConstVar(fun, _) | ExprX::StaticVar(fun) => {
                let name = self.op_name(fun);
                self.ensure_function(fun);
                name
            }
            ExprX::ReadPlace(place, _) => self.place(place, env),
            ExprX::Call { target, args, .. } => self.call(e, target, args, env),
            ExprX::Ctor(dt, variant, binders, tail) => self.ctor(e, dt, variant, binders, tail, env),
            ExprX::NullaryOpr(_) => self.refuse("nullary operator", &e.span),
            ExprX::Unary(op, inner) => match op {
                UnaryOp::Not => format!("~({})", self.expr(inner, env)),
                UnaryOp::Trigger(_) | UnaryOp::Clip { .. } | UnaryOp::CoerceMode { .. } => {
                    self.expr(inner, env)
                }
                UnaryOp::IntToReal | UnaryOp::RealToInt => self.expr(inner, env),
                _ => {
                    let what = format!("unary operator {:?}", op);
                    self.refuse(what, &e.span)
                }
            },
            ExprX::UnaryOpr(op, inner) => match op {
                UnaryOpr::Box(_) | UnaryOpr::Unbox(_) => self.expr(inner, env),
                UnaryOpr::HasType(_) => "TRUE".into(),
                UnaryOpr::IsVariant { datatype, variant } => {
                    let inner_s = self.expr(inner, env);
                    if self.single_variant(datatype) {
                        "TRUE".into()
                    } else {
                        format!("({inner_s}.tag = \"{variant}\")")
                    }
                }
                UnaryOpr::Field(FieldOpr { datatype, field, .. }) => {
                    if let Some(v) = read_var(inner) {
                        if let Some(role) = env.roles.get(&v) {
                            if matches!(datatype, Dt::Path(p) if *p == self.state_path) {
                                let prime = if *role == Role::Post { "'" } else { "" };
                                return format!("{}{prime}", field_name(field));
                            }
                        }
                    }
                    let inner_s = self.expr(inner, env);
                    self.field_access(&inner_s, datatype, field)
                }
                UnaryOpr::IntegerTypeBound(..) => self.refuse("integer type bound", &e.span),
                UnaryOpr::ProofNote(_) | UnaryOpr::CustomErr(_) => self.expr(inner, env),
                _ => {
                    let what = format!("unary operator {:?}", op);
                    self.refuse(what, &e.span)
                }
            },
            ExprX::Logical(op, a, b) => {
                // `post == e` on a whole state: one assignment per field.
                let (sa, sb) = (self.expr(a, env), self.expr(b, env));
                let sym = match op {
                    LogicalOp::And => "/\\",
                    LogicalOp::Or => "\\/",
                    LogicalOp::Implies => "=>",
                };
                format!("({sa} {sym} {sb})")
            }
            ExprX::Binary(op, a, b) => self.binary(e, op, a, b, env),
            ExprX::BinaryOpr(op, a, b) => match op {
                BinaryOpr::ExtEq(..) => {
                    format!("({} = {})", self.expr(a, env), self.expr(b, env))
                }
                _ => {
                    let what = format!("binary operator {:?}", op);
                    self.refuse(what, &e.span)
                }
            },
            ExprX::Multi(MultiOp::Chained(ops), args) => {
                let mut parts = Vec::new();
                for (i, op) in ops.iter().enumerate() {
                    let l = self.expr(&args[i], env);
                    let r = self.expr(&args[i + 1], env);
                    let sym = match op {
                        ChainedOp::Inequality(InequalityOp::Le) => "<=",
                        ChainedOp::Inequality(InequalityOp::Lt) => "<",
                        ChainedOp::Inequality(InequalityOp::Ge) => ">=",
                        ChainedOp::Inequality(InequalityOp::Gt) => ">",
                        ChainedOp::MultiEq => "=",
                    };
                    parts.push(format!("({l} {sym} {r})"));
                }
                format!("({})", parts.join(" /\\ "))
            }
            ExprX::Quant(q, binders, body) => self.quant(e, q, binders, body, env),
            ExprX::Closure(..) => self.refuse("closure outside a known call", &e.span),
            ExprX::Choose { .. } => self.refuse("choose (TLC cannot evaluate it)", &e.span),
            ExprX::WithTriggers { body, .. } => self.expr(body, env),
            ExprX::If(c, t, f) => {
                let (sc, st) = (self.expr(c, env), self.expr(t, env));
                let sf = match f {
                    Some(f) => self.expr(f, env),
                    None => "TRUE".into(),
                };
                format!("(IF {sc} THEN {st} ELSE {sf})")
            }
            ExprX::Match(place, arms, _) => self.matches(e, place, arms, env),
            ExprX::Block(stmts, tail) => self.block(e, stmts, tail, env),
            ExprX::Header(_) | ExprX::Fuel(..) | ExprX::RevealString(_) | ExprX::RevealByteString(_) => {
                "TRUE".into()
            }
            ExprX::AssertAssume { .. } | ExprX::AssertBy { .. } | ExprX::AssertQuery { .. } => {
                "TRUE".into()
            }
            _ => {
                let what = format!("expression kind {}", expr_kind(&e.x));
                self.refuse(what, &e.span)
            }
        }
    }

    fn binary(&mut self, e: &Expr, op: &BinaryOp, a: &Expr, b: &Expr, env: &Env) -> String {
        match op {
            BinaryOp::Eq(_) | BinaryOp::Ne => {
                let sym = if matches!(op, BinaryOp::Eq(_)) { "=" } else { "#" };
                // Whole-state equality with the post state on one side:
                // one primed assignment per field, so TLC can enumerate.
                if let Some(assign) = self.state_assignment(a, b, env) {
                    return if sym == "=" { assign } else { format!("~({assign})") };
                }
                format!("({} {sym} {})", self.expr(a, env), self.expr(b, env))
            }
            BinaryOp::Inequality(iq) => {
                let sym = match iq {
                    InequalityOp::Le => "<=",
                    InequalityOp::Ge => ">=",
                    InequalityOp::Lt => "<",
                    InequalityOp::Gt => ">",
                };
                format!("({} {sym} {})", self.expr(a, env), self.expr(b, env))
            }
            BinaryOp::Arith(ar) => {
                let sym = match ar {
                    ArithOp::Add(_) => "+",
                    ArithOp::Sub(_) => "-",
                    ArithOp::Mul(_) => "*",
                    ArithOp::EuclideanDiv(_) => "\\div",
                    ArithOp::EuclideanMod(_) => "%",
                };
                format!("({} {sym} {})", self.expr(a, env), self.expr(b, env))
            }
            BinaryOp::Xor => format!("({} # {})", self.expr(a, env), self.expr(b, env)),
            BinaryOp::Index(..) => {
                // Array or slice indexing: 0-based in Verus, 1-based here.
                format!("{}[({}) + 1]", self.expr(a, env), self.expr(b, env))
            }
            _ => {
                let what = format!("binary operator {:?}", op);
                self.refuse(what, &e.span)
            }
        }
    }

    /// `post == e` (either side) on the whole state, as per-field primed
    /// assignments; `pre == e` likewise unprimed.
    fn state_assignment(&mut self, a: &Expr, b: &Expr, env: &Env) -> Option<String> {
        let role_of = |x: &Expr| read_var(x).and_then(|v| env.roles.get(&v).copied());
        let (role, other) = match (role_of(a), role_of(b)) {
            (Some(r), None) => (r, b),
            (None, Some(r)) => (r, a),
            (Some(Role::Post), Some(Role::Pre)) | (Some(Role::Pre), Some(Role::Post)) => {
                let fields = self.state_field_names();
                return Some(format!(
                    "({})",
                    fields.iter().map(|f| format!("{f}' = {f}")).collect::<Vec<_>>().join(" /\\ ")
                ));
            }
            _ => return None,
        };
        let prime = if role == Role::Post { "'" } else { "" };
        let fields = self.state_field_names();
        // A constructor of the state type assigns field by field; anything
        // else is projected.
        if let ExprX::Ctor(Dt::Path(p), _variant, binders, tail) = &other.x {
            if *p == self.state_path {
                let mut parts = Vec::new();
                for f in &fields {
                    let given = binders.iter().find(|b| b.name.to_string() == *f);
                    let value = match given {
                        Some(b) => self.expr(&b.a, env),
                        None => match tail {
                            Some(t) => {
                                let base = self.place(&t.place, env);
                                format!("{base}.{f}")
                            }
                            None => "TRUE (* missing field *)".into(),
                        },
                    };
                    parts.push(format!("{f}{prime} = {value}"));
                }
                return Some(format!("({})", parts.join(" /\\ ")));
            }
        }
        let so = self.expr(other, env);
        Some(format!(
            "(LET s__ == {so} IN {})",
            fields.iter().map(|f| format!("{f}{prime} = s__.{f}")).collect::<Vec<_>>().join(" /\\ ")
        ))
    }

    fn single_variant(&self, dt: &Dt) -> bool {
        match dt {
            Dt::Path(p) => self.datatypes.get(p).map(|d| d.x.variants.len() == 1).unwrap_or(false),
            Dt::Tuple(_) => true,
        }
    }

    fn field_access(&mut self, base: &str, dt: &Dt, field: &Ident) -> String {
        match dt {
            Dt::Tuple(_) => {
                let idx: usize = field.parse().unwrap_or(0);
                format!("{base}[{}]", idx + 1)
            }
            Dt::Path(_) => format!("{base}.{}", field_name(field)),
        }
    }

    fn ctor(
        &mut self,
        e: &Expr,
        dt: &Dt,
        variant: &Ident,
        binders: &Binders<Expr>,
        tail: &Option<CtorUpdateTail>,
        env: &Env,
    ) -> String {
        match dt {
            Dt::Tuple(_) => {
                let mut items: Vec<(usize, String)> = binders
                    .iter()
                    .map(|b| (b.name.parse::<usize>().unwrap_or(0), self.expr(&b.a, env)))
                    .collect();
                items.sort_by_key(|(i, _)| *i);
                format!("<<{}>>", items.into_iter().map(|(_, s)| s).collect::<Vec<_>>().join(", "))
            }
            Dt::Path(p) => {
                let tagged = !self.single_variant(dt);
                if let Some(t) = tail {
                    let base = self.place(&t.place, env);
                    if binders.is_empty() {
                        return base;
                    }
                    let updates: Vec<String> = binders
                        .iter()
                        .map(|b| format!("!.{} = {}", field_name(&b.name), self.expr(&b.a, env)))
                        .collect();
                    return format!("[{base} EXCEPT {}]", updates.join(", "));
                }
                let mut fields: Vec<String> = Vec::new();
                if tagged {
                    fields.push(format!("tag |-> \"{variant}\""));
                }
                // Keep declaration order.
                let declared: Vec<Ident> = self
                    .datatypes
                    .get(p)
                    .and_then(|d| d.x.variants.iter().find(|v| &v.name == variant).map(|v| v.fields.iter().map(|f| f.name.clone()).collect()))
                    .unwrap_or_else(|| binders.iter().map(|b| b.name.clone()).collect());
                for name in declared {
                    if let Some(b) = binders.iter().find(|b| b.name == name) {
                        fields.push(format!("{} |-> {}", field_name(&name), self.expr(&b.a, env)));
                    }
                }
                if fields.is_empty() {
                    let _ = e;
                    "[tag |-> \"unit\"]".to_string()
                } else {
                    format!("[{}]", fields.join(", "))
                }
            }
        }
    }

    fn place(&mut self, p: &Place, env: &Env) -> String {
        match &p.x {
            PlaceX::Local(v) => {
                if let Some(role) = env.roles.get(v) {
                    self.state_record(*role)
                } else {
                    env.name(v)
                }
            }
            PlaceX::Field(FieldOpr { datatype, field, .. }, inner) => {
                if let Some(v) = place_var(inner) {
                    if let Some(role) = env.roles.get(&v) {
                        if matches!(datatype, Dt::Path(p) if *p == self.state_path) {
                            let prime = if *role == Role::Post { "'" } else { "" };
                            return format!("{}{prime}", field_name(field));
                        }
                    }
                }
                let base = self.place(inner, env);
                self.field_access(&base, datatype, field)
            }
            PlaceX::Temporary(e) | PlaceX::WithExpr(e, _) => self.expr(e, env),
            PlaceX::DerefMut(inner) | PlaceX::ModeUnwrap(inner, _) => self.place(inner, env),
            PlaceX::Index(inner, idx, _, _) => {
                format!("{}[({}) + 1]", self.place(inner, env), self.expr(idx, env))
            }
            PlaceX::UserDefinedTypInvariantObligation(inner, _) => self.place(inner, env),
        }
    }

    fn block(&mut self, e: &Expr, stmts: &Stmts, tail: &Option<Expr>, env: &Env) -> String {
        let mut env2 = env.clone();
        let mut lets = Vec::new();
        for s in stmts.iter() {
            match &s.x {
                StmtX::Decl { pattern, init: Some(init), .. } => match &pattern.x {
                    PatternX::Var(PatternBinding { name, .. }) => {
                        let value = self.place(init, &env2);
                        let n = ident_name(name);
                        env2.names.insert(name.clone(), n.clone());
                        if let PlaceX::Temporary(e) | PlaceX::WithExpr(e, _) = &init.x {
                            env2.values.insert(name.clone(), (peel(e), Box::new(env2.clone())));
                        }
                        lets.push(format!("{n} == {value}"));
                    }
                    PatternX::Wildcard(_) => {}
                    _ => {
                        let r = self.refuse("destructuring let", &s.span);
                        lets.push(format!("unused__ == {r}"));
                    }
                },
                StmtX::Decl { init: None, .. } => {}
                StmtX::Expr(x) => {
                    // A proof-mode statement in a spec body: nothing to print.
                    let _ = x;
                }
            }
        }
        let body = match tail {
            Some(t) => self.expr(t, &env2),
            None => "TRUE".into(),
        };
        let _ = e;
        if lets.is_empty() {
            body
        } else {
            format!("(LET {} IN {body})", lets.join("\n         "))
        }
    }

    fn matches(&mut self, e: &Expr, place: &Place, arms: &Arms, env: &Env) -> String {
        let scrutinee = self.place(place, env);
        // Bind the scrutinee once.
        let mut out = String::new();
        let mut chain: Vec<(String, String)> = Vec::new();
        let mut otherwise: Option<String> = None;
        for arm in arms.iter() {
            let mut env2 = env.clone();
            let (cond, lets) = self.pattern("m__", &arm.x.pattern, &mut env2);
            let guard = if matches!(arm.x.guard.x, ExprX::Const(Constant::Bool(true))) {
                None
            } else {
                Some(self.expr(&arm.x.guard, &env2))
            };
            let body = self.expr(&arm.x.body, &env2);
            let body = if lets.is_empty() { body } else { format!("(LET {} IN {body})", lets.join(" ")) };
            let cond = match (cond, guard) {
                (None, None) => None,
                (Some(c), None) => Some(c),
                (None, Some(g)) => Some(g),
                (Some(c), Some(g)) => Some(format!("({c} /\\ {g})")),
            };
            match cond {
                Some(c) => chain.push((c, body)),
                None => {
                    otherwise = Some(body);
                    break;
                }
            }
        }
        let mut tail = otherwise.unwrap_or_else(|| "TRUE (* no arm matched *)".into());
        for (c, b) in chain.into_iter().rev() {
            tail = format!("IF {c} THEN {b} ELSE {tail}");
        }
        out.push_str(&format!("(LET m__ == {scrutinee} IN {tail})"));
        let _ = e;
        out
    }

    /// The condition a pattern imposes on `subject`, and the LET bindings it
    /// introduces (added to `env`).
    fn pattern(&mut self, subject: &str, p: &Pattern, env: &mut Env) -> (Option<String>, Vec<String>) {
        match &p.x {
            PatternX::Wildcard(_) => (None, vec![]),
            PatternX::Var(PatternBinding { name, .. }) => {
                let n = ident_name(name);
                env.names.insert(name.clone(), n.clone());
                (None, vec![format!("{n} == {subject}")])
            }
            PatternX::Binding { binding: PatternBinding { name, .. }, sub_pat } => {
                let n = ident_name(name);
                env.names.insert(name.clone(), n.clone());
                let (c, mut lets) = self.pattern(subject, sub_pat, env);
                lets.insert(0, format!("{n} == {subject}"));
                (c, lets)
            }
            PatternX::Constructor(dt, variant, binders) => {
                let mut conds = Vec::new();
                if !self.single_variant(dt) {
                    conds.push(format!("({subject}.tag = \"{variant}\")"));
                }
                let mut lets = Vec::new();
                for b in binders.iter() {
                    let field = self.field_access(subject, dt, &b.name);
                    let (c, l) = self.pattern(&field, &b.a, env);
                    if let Some(c) = c {
                        conds.push(c);
                    }
                    lets.extend(l);
                }
                (if conds.is_empty() { None } else { Some(conds.join(" /\\ ")) }, lets)
            }
            PatternX::Or(..) => {
                let r = self.refuse("or-pattern", &p.span);
                (Some(r), vec![])
            }
            _ => {
                let r = self.refuse("pattern kind", &p.span);
                (Some(r), vec![])
            }
        }
    }

    // ─── calls ──────────────────────────────────────────────────────────

    fn call(&mut self, e: &Expr, target: &CallTarget, args: &Exprs, env: &Env) -> String {
        match target {
            CallTarget::Fun(_, fun, _typs, _, _) => {
                let friendly = fun_as_friendly_rust_name(fun);
                if let Some(op) = vstd_op(&friendly) {
                    return self.vstd_call(e, op, args, env);
                }
                // Option and other core datatypes' spec helpers.
                if friendly.ends_with("::is_some") || friendly.ends_with("::is_Some") {
                    return format!("({}.tag = \"Some\")", self.expr(&args[0], env));
                }
                if friendly.ends_with("::is_none") || friendly.ends_with("::is_None") {
                    return format!("({}.tag = \"None\")", self.expr(&args[0], env));
                }
                if friendly.ends_with("::unwrap") || friendly.ends_with("::get_Some_0") || friendly.ends_with("::arrow_Some_0") {
                    return format!("{}.v0", self.expr(&args[0], env));
                }
                let Some(callee) = self.functions.get(fun).cloned() else {
                    let what = format!("call to {friendly} (no definition in the crate)");
                    return self.refuse(what, &e.span);
                };
                // A state-typed argument passed to a state-role parameter of
                // the callee is dropped, and the whole application is primed
                // when the callee's single state parameter receives `post`.
                let roles = self.param_roles(&callee);
                let mut printed = Vec::new();
                let mut prime = false;
                let mut pre_given = false;
                for (i, a) in args.iter().enumerate() {
                    let arg_role = read_var(a).and_then(|v| env.roles.get(&v).copied());
                    match roles.get(i).copied().flatten() {
                        Some(Role::Pre) => match arg_role {
                            Some(Role::Pre) => pre_given = true,
                            Some(Role::Post) => {
                                if roles.iter().filter(|r| r.is_some()).count() == 1 {
                                    prime = true;
                                } else {
                                    let r = self.refuse("post state passed where the callee expects its pre state", &a.span);
                                    printed.push(r);
                                }
                            }
                            None => {
                                let r = self.refuse("a computed state passed to a state operator", &a.span);
                                printed.push(r);
                            }
                        },
                        Some(Role::Post) => {
                            if arg_role != Some(Role::Post) {
                                let r = self.refuse("something other than the post state passed as a callee's post state", &a.span);
                                printed.push(r);
                            }
                        }
                        None => printed.push(self.expr(a, env)),
                    }
                }
                let _ = pre_given;
                let name = self.op_name(fun);
                self.ensure_function(fun);
                let app = if printed.is_empty() { name } else { format!("{name}({})", printed.join(", ")) };
                if prime { format!("({app})'") } else { app }
            }
            CallTarget::FnSpec(f) => {
                if let Some((params, body, mut env2, mut lets)) = self.resolve_closure(f, env, 0) {
                    for (p, a) in params.iter().zip(args.iter()) {
                        match read_var(a).and_then(|v| env.roles.get(&v).copied()) {
                            Some(role) => {
                                env2.roles.insert(p.name.clone(), role);
                            }
                            _ => {
                                let n = ident_name(&p.name);
                                env2.names.insert(p.name.clone(), n.clone());
                                env2.values.insert(p.name.clone(), (peel(a), Box::new(env.clone())));
                                if !typ_has_specfn(&p.a, &self.datatypes, &mut HashSet::new()) {
                                    lets.push(format!("{n} == {}", self.expr(a, env)));
                                }
                            }
                        }
                    }
                    let b = self.expr(&body, &env2);
                    return if lets.is_empty() { b } else { format!("(LET {} IN {b})", lets.join(" ")) };
                }
                self.refuse("application of a spec_fn value that does not reduce to a closure", &e.span)
            }
            CallTarget::BuiltinSpecFun(..) => self.refuse("call_requires/call_ensures", &e.span),
            CallTarget::AssumeExternal => self.refuse("external call", &e.span),
        }
    }

    /// Reduce an expression to a closure literal: a literal, a variable bound
    /// to one, a field of a record bound to one, or a call whose body is
    /// one (its parameters become LET bindings or symbolic values). Returns
    /// the closure's parameters and body with the environment to print the
    /// body in, plus the LET bindings that environment relies on.
    fn resolve_closure(&mut self, f: &Expr, env: &Env, depth: usize) -> Option<(VarBinders<Typ>, Expr, Env, Vec<String>)> {
        if depth > 16 {
            return None;
        }
        let f = peel(f);
        match &f.x {
            ExprX::Closure(params, body) => Some((params.clone(), body.clone(), env.clone(), vec![])),
            ExprX::Var(v) => {
                let (value, venv) = env.values.get(v)?.clone();
                self.resolve_closure(&value, &venv, depth + 1)
            }
            ExprX::ReadPlace(p, _) => self.resolve_place_closure(p, env, depth + 1),
            ExprX::UnaryOpr(UnaryOpr::Field(FieldOpr { field, .. }), inner) => {
                let (record, renv) = self.resolve_record(inner, env, depth + 1)?;
                if let ExprX::Ctor(_, _, binders, _) = &record.x {
                    let b = binders.iter().find(|b| &b.name == field)?;
                    return self.resolve_closure(&b.a, &renv, depth + 1);
                }
                None
            }
            ExprX::Call { target: CallTarget::Fun(_, fun, ..), args, .. } => {
                let callee = self.functions.get(fun).cloned()?;
                let body = callee.x.body.clone()?;
                let mut env2 = Env::new();
                let mut lets = Vec::new();
                for (p, a) in callee.x.params.iter().zip(args.iter()) {
                    // An argument that is the pre or post state makes the
                    // parameter a state parameter, whatever its declared
                    // type (a generic `State` in verus-tla's Action).
                    match read_var(a).and_then(|v| env.roles.get(&v).copied()) {
                        Some(role) => {
                            env2.roles.insert(p.x.name.clone(), role);
                        }
                        _ => {
                            let n = ident_name(&p.x.name);
                            env2.names.insert(p.x.name.clone(), n.clone());
                            env2.values.insert(p.x.name.clone(), (peel(a), Box::new(env.clone())));
                            if !typ_has_specfn(&p.x.typ, &self.datatypes, &mut HashSet::new()) {
                                lets.push(format!("{n} == {}", self.expr(a, env)));
                            }
                        }
                    }
                }
                let (params, cbody, cenv, mut clets) = self.resolve_closure(&body, &env2, depth + 1)?;
                lets.append(&mut clets);
                Some((params, cbody, cenv, lets))
            }
            _ => None,
        }
    }

    fn resolve_place_closure(&mut self, p: &Place, env: &Env, depth: usize) -> Option<(VarBinders<Typ>, Expr, Env, Vec<String>)> {
        match &p.x {
            PlaceX::Local(v) => {
                let (value, venv) = env.values.get(v)?.clone();
                self.resolve_closure(&value, &venv, depth + 1)
            }
            PlaceX::Field(FieldOpr { field, .. }, inner) => {
                let (record, renv) = self.resolve_record_place(inner, env, depth + 1)?;
                if let ExprX::Ctor(_, _, binders, _) = &record.x {
                    let b = binders.iter().find(|b| &b.name == field)?;
                    return self.resolve_closure(&b.a, &renv, depth + 1);
                }
                None
            }
            PlaceX::Temporary(e) | PlaceX::WithExpr(e, _) => self.resolve_closure(e, env, depth + 1),
            PlaceX::DerefMut(inner) | PlaceX::ModeUnwrap(inner, _) => self.resolve_place_closure(inner, env, depth + 1),
            _ => None,
        }
    }

    /// Reduce an expression to a record constructor, through variables and
    /// calls whose body is one.
    fn resolve_record(&mut self, e: &Expr, env: &Env, depth: usize) -> Option<(Expr, Env)> {
        if depth > 16 {
            return None;
        }
        let e = peel(e);
        match &e.x {
            ExprX::Ctor(..) => Some((e.clone(), env.clone())),
            ExprX::Var(v) => {
                let (value, venv) = env.values.get(v)?.clone();
                self.resolve_record(&value, &venv, depth + 1)
            }
            ExprX::ReadPlace(p, _) => self.resolve_record_place(p, env, depth + 1),
            ExprX::Call { target: CallTarget::Fun(_, fun, ..), args, .. } => {
                let callee = self.functions.get(fun).cloned()?;
                let body = callee.x.body.clone()?;
                let mut env2 = Env::new();
                for (p, a) in callee.x.params.iter().zip(args.iter()) {
                    env2.names.insert(p.x.name.clone(), ident_name(&p.x.name));
                    env2.values.insert(p.x.name.clone(), (peel(a), Box::new(env.clone())));
                }
                self.resolve_record(&body, &env2, depth + 1)
            }
            _ => None,
        }
    }

    fn resolve_record_place(&mut self, p: &Place, env: &Env, depth: usize) -> Option<(Expr, Env)> {
        match &p.x {
            PlaceX::Local(v) => {
                let (value, venv) = env.values.get(v)?.clone();
                self.resolve_record(&value, &venv, depth + 1)
            }
            PlaceX::Temporary(e) | PlaceX::WithExpr(e, _) => self.resolve_record(e, env, depth + 1),
            PlaceX::DerefMut(inner) | PlaceX::ModeUnwrap(inner, _) => self.resolve_record_place(inner, env, depth + 1),
            _ => None,
        }
    }

    fn vstd_call(&mut self, e: &Expr, op: &str, args: &Exprs, env: &Env) -> String {
        let a: Vec<String> = args.iter().map(|x| self.expr(x, env)).collect();
        let g = |i: usize| a.get(i).cloned().unwrap_or_else(|| "TRUE".into());
        match op {
            "seq_len" => format!("Len({})", g(0)),
            "seq_index" => format!("{}[({}) + 1]", g(0), g(1)),
            "seq_push" => format!("Append({}, {})", g(0), g(1)),
            "seq_update" => format!("[{} EXCEPT ![({}) + 1] = {}]", g(0), g(1), g(2)),
            "seq_subrange" => format!("SubSeq({}, ({}) + 1, {})", g(0), g(1), g(2)),
            "seq_add" => format!("({} \\o {})", g(0), g(1)),
            "seq_empty" => "<< >>".into(),
            "seq_last" => format!("(LET s__ == {} IN s__[Len(s__)])", g(0)),
            "seq_first" => format!("{}[1]", g(0)),
            "seq_drop_first" => format!("Tail({})", g(0)),
            "seq_drop_last" => format!("(LET s__ == {} IN SubSeq(s__, 1, Len(s__) - 1))", g(0)),
            "seq_take" => format!("SubSeq({}, 1, {})", g(0), g(1)),
            "seq_skip" => format!("(LET s__ == {} IN SubSeq(s__, ({}) + 1, Len(s__)))", g(0), g(1)),
            "seq_contains" => format!("(LET s__ == {} IN \\E i__ \\in 1..Len(s__) : s__[i__] = {})", g(0), g(1)),
            "seq_new" => {
                if let ExprX::Closure(params, body) = &args[1].x {
                    let mut env2 = env.clone();
                    let n = ident_name(&params[0].name);
                    env2.names.insert(params[0].name.clone(), n.clone());
                    let b = self.expr(body, &env2);
                    format!("[i__ \\in 1..({}) |-> LET {n} == i__ - 1 IN {b}]", g(0))
                } else {
                    self.refuse("Seq::new with a non-literal function", &e.span)
                }
            }
            "set_contains" => format!("({} \\in {})", g(1), g(0)),
            "set_insert" => format!("({} \\cup {{{}}})", g(0), g(1)),
            "set_remove" => format!("({} \\ {{{}}})", g(0), g(1)),
            "set_empty" => "{}".into(),
            "set_union" => format!("({} \\cup {})", g(0), g(1)),
            "set_intersect" => format!("({} \\cap {})", g(0), g(1)),
            "set_difference" => format!("({} \\ {})", g(0), g(1)),
            "set_subset_of" => format!("({} \\subseteq {})", g(0), g(1)),
            "set_len" => format!("Cardinality({})", g(0)),
            "set_finite" => format!("IsFiniteSet({})", g(0)),
            "set_is_empty" => format!("({} = {{}})", g(0)),
            "set_full" => self.refuse("Set::full (unbounded)", &e.span),
            "ext_equal" => format!("({} = {})", g(0), g(1)),
            "map_dom" => format!("DOMAIN {}", g(0)),
            "map_index" => format!("{}[{}]", g(0), g(1)),
            "map_insert" => format!("(({} :> {}) @@ {})", g(1), g(2), g(0)),
            "map_remove" => format!("(LET m__ == {} IN [k__ \\in (DOMAIN m__) \\ {{{}}} |-> m__[k__]])", g(0), g(1)),
            "map_empty" => "[k__ \\in {} |-> k__]".into(),
            "map_contains_key" => format!("({} \\in DOMAIN {})", g(1), g(0)),
            "map_len" => format!("Cardinality(DOMAIN {})", g(0)),
            "map_values" => format!("(LET m__ == {} IN {{m__[k__] : k__ \\in DOMAIN m__}})", g(0)),
            _ => self.refuse(format!("vstd operation {op}"), &e.span),
        }
    }

    // ─── quantifiers ────────────────────────────────────────────────────

    fn quant(&mut self, e: &Expr, q: &Quant, binders: &VarBinders<Typ>, body: &Expr, env: &Env) -> String {
        let forall = matches!(q.quant, air::ast::Quant::Forall);
        let mut env2 = env.clone();
        for b in binders.iter() {
            let n = ident_name(&b.name);
            env2.names.insert(b.name.clone(), n);
        }
        // The guard: the antecedent of an implication (forall) or the
        // conjuncts (exists).
        let guard_exprs: Vec<Expr> = match (&body.x, forall) {
            (ExprX::Logical(LogicalOp::Implies, g, _), true) => conjuncts(g),
            (ExprX::Logical(LogicalOp::And, _, _), false) => conjuncts(body),
            _ => vec![],
        };
        let mut bounds = Vec::new();
        for b in binders.iter() {
            let name = env2.name(&b.name);
            let domain = match self.bound_from_guard(&b.name, &b.a, &guard_exprs, &env2) {
                Some(d) => d,
                None => match self.bound_from_type(&b.a, &e.span) {
                    Some(d) => d,
                    None => {
                        let constant = format!("Dom_{}", sanitize(&typ_name(&b.a)));
                        self.constants.insert(constant.clone());
                        self.holes.push(Hole {
                            variable: name.clone(),
                            typ: typ_name(&b.a),
                            constant: constant.clone(),
                            location: span_string(&e.span),
                            in_function: self.current.clone(),
                        });
                        constant
                    }
                },
            };
            bounds.push(format!("{name} \\in {domain}"));
        }
        let sb = self.expr(body, &env2);
        format!("({} {} : {sb})", if forall { "\\A" } else { "\\E" }, bounds.join(", "))
    }

    /// A finite domain from the type alone: booleans, and enums whose
    /// variants' fields are themselves bounded (a variant's field of an
    /// unbounded type becomes a hole constant of its own).
    fn bound_from_type(&mut self, typ: &Typ, span: &crate::messages::Span) -> Option<String> {
        match &**typ {
            TypX::Bool => Some("BOOLEAN".into()),
            TypX::Datatype(Dt::Path(p), _, _) => {
                let d = self.datatypes.get(p)?.clone();
                if d.x.variants.len() < 2 && d.x.variants.iter().all(|v| v.fields.is_empty()) {
                    return None;
                }
                let tagged = d.x.variants.len() > 1;
                let mut parts = Vec::new();
                for v in d.x.variants.iter() {
                    if v.name.to_string() == "dummy_to_use_type_params" {
                        continue;
                    }
                    let mut fields = Vec::new();
                    if tagged {
                        fields.push(format!("tag |-> \"{}\"", v.name));
                    }
                    let mut binds = Vec::new();
                    for f in v.fields.iter() {
                        let fname = field_name(&f.name);
                        let domain = match self.bound_from_type(&f.a.0, span) {
                            Some(dom) => dom,
                            None => {
                                let constant = format!("Dom_{}_{}_{}", sanitize(&last_segment(p)), sanitize(&v.name), fname);
                                self.constants.insert(constant.clone());
                                self.holes.push(Hole {
                                    variable: format!("{}.{}", v.name, fname),
                                    typ: typ_name(&f.a.0),
                                    constant: constant.clone(),
                                    location: span_string(span),
                                    in_function: self.current.clone(),
                                });
                                constant
                            }
                        };
                        fields.push(format!("{fname} |-> {fname}__"));
                        binds.push(format!("{fname}__ \\in {domain}"));
                    }
                    let record = format!("[{}]", fields.join(", "));
                    if binds.is_empty() {
                        parts.push(format!("{{{record}}}"));
                    } else {
                        parts.push(format!("{{{record} : {}}}", binds.join(", ")));
                    }
                }
                if parts.is_empty() {
                    None
                } else {
                    Some(format!("({})", parts.join(" \\cup ")))
                }
            }
            TypX::Decorate(_, _, t) | TypX::Boxed(t) => self.bound_from_type(t, span),
            _ => None,
        }
    }

    /// A finite domain for `v` read off the guard's conjuncts: membership in
    /// a set, a map's domain, or an integer range from inequalities.
    fn bound_from_guard(&mut self, v: &VarIdent, typ: &Typ, guard: &[Expr], env: &Env) -> Option<String> {
        let is_v = |x: &Expr| matches!(&x.x, ExprX::Var(u) if u == v);
        let _ = typ;
        // Membership.
        for g in guard {
            if let ExprX::Call { target: CallTarget::Fun(_, fun, ..), args, .. } = &g.x {
                let name = fun_as_friendly_rust_name(fun);
                match vstd_op(&name) {
                    Some("set_contains") if args.len() == 2 && is_v(&args[1]) && !mentions(&args[0], v) => {
                        return Some(self.expr(&args[0], env));
                    }
                    Some("map_contains_key") if args.len() == 2 && is_v(&args[1]) && !mentions(&args[0], v) => {
                        return Some(format!("DOMAIN {}", self.expr(&args[0], env)));
                    }
                    Some("seq_contains") if args.len() == 2 && is_v(&args[1]) && !mentions(&args[0], v) => {
                        let s = self.expr(&args[0], env);
                        return Some(format!("{{{s}[i__] : i__ \\in 1..Len({s})}}"));
                    }
                    _ => {}
                }
            }
        }
        // Integer range from inequalities and chained comparisons.
        let mut lower: Option<String> = None;
        let mut upper: Option<String> = None;
        let mut note = |side: &Expr, op: InequalityOp, other: &Expr, this: &mut Self, lower: &mut Option<String>, upper: &mut Option<String>| {
            // side is v; the comparison is `v op other`.
            let _ = side;
            if mentions(other, v) {
                return;
            }
            let o = this.expr(other, env);
            match op {
                InequalityOp::Ge => *lower = Some(o),
                InequalityOp::Gt => *lower = Some(format!("({o}) + 1")),
                InequalityOp::Le => *upper = Some(o),
                InequalityOp::Lt => *upper = Some(format!("({o}) - 1")),
            }
        };
        let flip = |op: &InequalityOp| match op {
            InequalityOp::Le => InequalityOp::Ge,
            InequalityOp::Ge => InequalityOp::Le,
            InequalityOp::Lt => InequalityOp::Gt,
            InequalityOp::Gt => InequalityOp::Lt,
        };
        for g in guard {
            match &g.x {
                ExprX::Binary(BinaryOp::Inequality(op), a, b) => {
                    if is_v(a) {
                        note(a, *op, b, self, &mut lower, &mut upper);
                    } else if is_v(b) {
                        note(b, flip(op), a, self, &mut lower, &mut upper);
                    }
                }
                ExprX::Multi(MultiOp::Chained(ops), args) => {
                    for (i, op) in ops.iter().enumerate() {
                        if let ChainedOp::Inequality(op) = op {
                            let (a, b) = (&args[i], &args[i + 1]);
                            if is_v(a) {
                                note(a, *op, b, self, &mut lower, &mut upper);
                            } else if is_v(b) {
                                note(b, flip(op), a, self, &mut lower, &mut upper);
                            }
                        }
                    }
                }
                _ => {}
            }
        }
        match (lower, upper) {
            (Some(l), Some(u)) => Some(format!("{l}..{u}")),
            _ => None,
        }
    }

    // ─── functions ──────────────────────────────────────────────────────

    /// The role of each parameter: a state-typed parameter is pre or post
    /// (the first one pre, a second one post), any other is None.
    fn param_roles(&self, f: &Function) -> Vec<Option<Role>> {
        let mut seen = 0;
        f.x.params
            .iter()
            .map(|p| {
                if self.is_state_typ(&p.x.typ) {
                    seen += 1;
                    Some(if seen == 1 { Role::Pre } else { Role::Post })
                } else {
                    None
                }
            })
            .collect()
    }

    fn ensure_function(&mut self, fun: &Fun) {
        if self.emitted.contains(fun) || self.emitting.contains(fun) {
            return;
        }
        let Some(f) = self.functions.get(fun).cloned() else { return };
        self.emitting.insert(fun.clone());
        let name = self.op_name(fun);
        let previous = std::mem::replace(&mut self.current, fun_as_friendly_rust_name(fun));
        let mut env = Env::new();
        let roles = self.param_roles(&f);
        let mut params = Vec::new();
        for (p, role) in f.x.params.iter().zip(roles.iter()) {
            match role {
                Some(r) => {
                    env.roles.insert(p.x.name.clone(), *r);
                }
                None => {
                    let n = ident_name(&p.x.name);
                    env.names.insert(p.x.name.clone(), n.clone());
                    params.push(n);
                }
            }
        }
        let body = match &f.x.body {
            Some(b) => self.expr(b, &env),
            None => {
                let r = self.refuse("uninterpreted function", &f.span);
                r
            }
        };
        let head = if params.is_empty() { name.clone() } else { format!("{name}({})", params.join(", ")) };
        let mut def = String::new();
        def.push_str(&format!("\\* {}, {}\n", fun_as_friendly_rust_name(fun), span_string(&f.span)));
        if f.x.decrease.len() > 0 || self.recursive.contains(&name) {
            self.recursive.insert(name.clone());
        }
        def.push_str(&format!("{head} ==\n    {body}\n"));
        self.defs.push(def);
        self.current = previous;
        self.emitting.remove(fun);
        self.emitted.insert(fun.clone());
    }
}

fn field_name(f: &Ident) -> String {
    let s = f.to_string();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        format!("v{s}")
    } else {
        s
    }
}

fn expr_kind(x: &ExprX) -> &'static str {
    match x {
        ExprX::Loop { .. } => "loop",
        ExprX::Assign { .. } => "assignment",
        ExprX::NonSpecClosure { .. } => "exec closure",
        ExprX::ArrayLiteral(_) => "array literal",
        ExprX::ExecFnByName(_) => "function by name",
        ExprX::OpenInvariant(..) => "open invariant",
        ExprX::Return(_) => "return",
        ExprX::BreakOrContinue { .. } => "break/continue",
        ExprX::Ghost { .. } => "ghost block",
        _ => "unsupported",
    }
}

/// The recognised triple.
struct Triple {
    shape: &'static str,
    state: Path,
    init: Fun,
    next: Fun,
    invariants: Vec<Fun>,
}

fn module_of(f: &Function) -> Option<Path> {
    f.x.owning_module.clone()
}

fn recognise(krate: &Krate, module: &str) -> Result<Triple, String> {
    let in_module: Vec<Function> = krate
        .functions
        .iter()
        .filter(|f| module_of(f).map(|m| path_as_friendly_rust_name(&m) == module).unwrap_or(false))
        .cloned()
        .collect();
    if in_module.is_empty() {
        let known: BTreeSet<String> =
            krate.functions.iter().filter_map(module_of).map(|m| path_as_friendly_rust_name(&m)).collect();
        return Err(format!(
            "no functions in module `{module}`; modules with functions: {}",
            known.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    let short = |f: &Function| last_segment(&f.x.name.path);
    let state_of = |f: &Function| f.x.params.first().and_then(|p| typ_datatype(&p.x.typ));
    let is_bool = |f: &Function| matches!(&*f.x.ret.x.typ, TypX::Bool);
    // Hand-rolled or VerusSync: `next(pre, post)` with two params of one datatype.
    let next = in_module.iter().find(|f| short(f) == "next" && f.x.params.len() == 2 && is_bool(f) && state_of(f).is_some() && state_of(f) == f.x.params.get(1).and_then(|p| typ_datatype(&p.x.typ)));
    if let Some(next) = next {
        let state = state_of(next).unwrap();
        let init = in_module
            .iter()
            .find(|f| short(f) == "init" && f.x.params.len() == 1 && is_bool(f) && state_of(f).as_ref() == Some(&state))
            .ok_or_else(|| format!("found `next` in `{module}` but no `init(s: State) -> bool` beside it"))?;
        let shape = if in_module.iter().any(|f| short(f) == "next_by") { "verussync" } else { "hand-rolled" };
        let invariants: Vec<Fun> = in_module
            .iter()
            .filter(|f| {
                f.x.params.len() == 1
                    && is_bool(f)
                    && state_of(f).as_ref() == Some(&state)
                    && short(f) != "init"
                    && f.x.mode == Mode::Spec
                    && f.x.body.is_some()
                    && !matches!(short(f).as_str(), "next" | "next_by" | "init_by" | "invariant")
            })
            .map(|f| f.x.name.clone())
            .collect();
        return Ok(Triple { shape, state, init: init.x.name.clone(), next: next.x.name.clone(), invariants });
    }
    // verus-tla: `next()` returning a spec_fn over (S, S).
    let next = in_module.iter().find(|f| short(f) == "next" && f.x.params.is_empty() && matches!(&*f.x.ret.x.typ, TypX::SpecFn(ps, r) if ps.len() == 2 && matches!(&**r, TypX::Bool)));
    if let Some(next) = next {
        let state = match &*next.x.ret.x.typ {
            TypX::SpecFn(ps, _) => typ_datatype(&ps[0]).ok_or("state type of `next()` is not a datatype")?,
            _ => unreachable!(),
        };
        let init = in_module
            .iter()
            .find(|f| short(f) == "init" && f.x.params.is_empty() && matches!(&*f.x.ret.x.typ, TypX::SpecFn(ps, _) if ps.len() == 1))
            .ok_or("found verus-tla `next()` but no `init()`")?;
        let invariants: Vec<Fun> = in_module
            .iter()
            .filter(|f| f.x.params.is_empty() && matches!(&*f.x.ret.x.typ, TypX::SpecFn(ps, r) if ps.len() == 1 && matches!(&**r, TypX::Bool)) && short(f) != "init")
            .map(|f| f.x.name.clone())
            .collect();
        return Ok(Triple { shape: "verus-tla", state, init: init.x.name.clone(), next: next.x.name.clone(), invariants });
    }
    Err(format!("no transition system found in `{module}`: expected `next(pre, post) -> bool` and `init(s) -> bool`, or verus-tla's `next()`/`init()` closures"))
}

/// Export the transition system in `module` (a `crate::a::b` path as Verus
/// prints it) to TLA+.
pub fn export_module(krate: &Krate, module: &str) -> Result<Export, String> {
    let triple = recognise(krate, module)?;
    let datatypes: HashMap<Path, Datatype> = krate
        .datatypes
        .iter()
        .filter_map(|d| match &d.x.name {
            Dt::Path(p) => Some((p.clone(), d.clone())),
            Dt::Tuple(_) => None,
        })
        .collect();
    let functions: HashMap<Fun, Function> = krate.functions.iter().map(|f| (f.x.name.clone(), f.clone())).collect();
    let state_dt = datatypes.get(&triple.state).ok_or("state datatype not found")?.clone();
    let state_fields: Vec<String> =
        state_dt.x.variants.first().map(|v| v.fields.iter().map(|f| field_name(&f.name)).collect()).unwrap_or_default();
    if state_dt.x.variants.len() != 1 {
        return Err("the state type must be a struct".into());
    }
    let mut ex = Exporter {
        krate,
        datatypes,
        functions,
        state_path: triple.state.clone(),
        state_fields: state_fields.clone(),
        defs: Vec::new(),
        emitted: HashSet::new(),
        emitting: HashSet::new(),
        recursive: BTreeSet::new(),
        op_names: HashMap::new(),
        used_names: HashSet::new(),
        holes: Vec::new(),
        refusals: Vec::new(),
        constants: BTreeSet::new(),
        current: String::new(),
    };
    for f in &state_fields {
        ex.used_names.insert(f.clone());
    }
    for reserved in ["Init", "Next", "Spec", "vars", "Inv", "TypeOK"] {
        ex.used_names.insert(reserved.into());
    }
    let mut roots = vec![triple.init.clone(), triple.next.clone()];
    roots.extend(triple.invariants.iter().cloned());
    let _ = &roots;
    // verus-tla: the closures are the bodies; emit as state operators by
    // treating `init()`/`next()` specially.
    let verus_tla = triple.shape == "verus-tla";
    let mut init_name = String::new();
    let mut next_name = String::new();
    let mut inv_names = Vec::new();
    if verus_tla {
        for (i, r) in roots.iter().enumerate() {
            let f = ex.functions.get(r).cloned().ok_or("root missing")?;
            let name = ex.op_name(r);
            ex.current = fun_as_friendly_rust_name(r);
            let body = match &f.x.body {
                Some(b) => match &peel(b).x {
                    ExprX::Closure(params, body) => {
                        let mut env = Env::new();
                        for (k, p) in params.iter().enumerate() {
                            env.roles.insert(p.name.clone(), if k == 0 { Role::Pre } else { Role::Post });
                        }
                        ex.expr(body, &env)
                    }
                    _ => ex.refuse("verus-tla root whose body is not a closure literal", &b.span),
                },
                None => ex.refuse("root without a body", &f.span),
            };
            ex.defs.push(format!("\\* {}, {}\n{name} ==\n    {body}\n", fun_as_friendly_rust_name(r), span_string(&f.span)));
            ex.emitted.insert(r.clone());
            match i {
                0 => init_name = name,
                1 => next_name = name,
                _ => inv_names.push(name),
            }
        }
    } else {
        ex.ensure_function(&triple.init);
        init_name = ex.op_name(&triple.init);
        ex.ensure_function(&triple.next);
        next_name = ex.op_name(&triple.next);
        // Everything reached from init and next is a transition or a helper,
        // not an invariant, whatever its signature.
        let transitions: HashSet<Fun> = ex.emitted.clone();
        for r in &triple.invariants {
            if transitions.contains(r) {
                continue;
            }
            ex.ensure_function(r);
            inv_names.push(ex.op_name(r));
        }
    }
    let module_name = format!("{}_tla", sanitize(&last_segment(&triple.state)));
    let mut tla = String::new();
    tla.push_str(&format!("---- MODULE {module_name} ----\n"));
    tla.push_str("\\* Exported by verus -V tla-export from the Verus model in `");
    tla.push_str(module);
    tla.push_str("`.\n\\* Mapping: structs are records; enum values are records with a `tag`;\n");
    tla.push_str("\\* Seq is a 1-based sequence (every index shifted once); Set is a set;\n");
    tla.push_str("\\* Map is a function (dom = DOMAIN, insert = :> @@); Option is a record tagged\n");
    tla.push_str("\\* None/Some with field v0; nat/int/uN are Int; a spec fn is an operator, its\n");
    tla.push_str("\\* pre/post state parameters dropped and read as the unprimed/primed variables;\n");
    tla.push_str("\\* a quantifier is bounded from its guard, or from a CONSTANT Dom_<Type>.\n");
    tla.push_str("EXTENDS Integers, Sequences, FiniteSets, TLC\n\n");
    if !ex.constants.is_empty() {
        tla.push_str(&format!("CONSTANTS {}\n\n", ex.constants.iter().cloned().collect::<Vec<_>>().join(", ")));
    }
    tla.push_str(&format!("VARIABLES {}\n", state_fields.join(", ")));
    tla.push_str(&format!("vars == <<{}>>\n\n", state_fields.join(", ")));
    if !ex.recursive.is_empty() {
        for r in &ex.recursive {
            tla.push_str(&format!("RECURSIVE {r}(_)\n"));
        }
        tla.push('\n');
    }
    for d in &ex.defs {
        tla.push_str(d);
        tla.push('\n');
    }
    tla.push_str(&format!("Init == {init_name}\n"));
    tla.push_str(&format!("Next == {next_name}\n"));
    tla.push_str("Spec == Init /\\ [][Next]_vars\n");
    if !inv_names.is_empty() {
        tla.push_str(&format!("Inv == {}\n", inv_names.iter().map(|n| format!("({n})")).collect::<Vec<_>>().join(" /\\ ")));
    }
    tla.push_str(&format!("{}\n", "=".repeat(module_name.len() + 20)));

    let mut cfg = String::new();
    cfg.push_str("SPECIFICATION Spec\n");
    if !inv_names.is_empty() {
        cfg.push_str("INVARIANTS\n");
        for n in &inv_names {
            cfg.push_str(&format!("  {n}\n"));
        }
    }
    if !ex.constants.is_empty() {
        cfg.push_str("\\* Domains the export could not bound; give each a finite set.\nCONSTANTS\n");
        for c in &ex.constants {
            cfg.push_str(&format!("  {c} = {{}}\n"));
        }
    }
    cfg.push_str("\\* CONSTRAINT <a state predicate bounding the model>\n");
    let report = Report {
        module: module.to_string(),
        shape: triple.shape.to_string(),
        state_type: path_as_friendly_rust_name(&triple.state),
        variables: state_fields,
        init: init_name,
        next: next_name,
        actions: Vec::new(),
        invariants: inv_names,
        operators: ex.defs.len(),
        holes: ex.holes,
        refusals: ex.refusals,
    };
    Ok(Export { tla, cfg, report })
}
